#Specify the version of docker-compose to use
version: "3"
services: 
    web:
    #use a Docker file in the current directory to create an image
      build: 
        context: .
        dockerfile: Dockerfile.dev
    #Correct port mapping to container
      ports: 
        - "3000:3000"
      volumes: 
      #Map the node module folder
        - /app/node_modules
      #Map the current folder to the container /usr/app folder
        - .:/app
#To run the test
    test:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      volumes: 
        - /app/node_modules
        - .:/app
      command: ["npm", "run", "test"]